# dsbot-hakaton.py
пятое задание для хакатона
из-за ошибки с интернетом на нашей стороне, мы не успели загрузить файл
